# docker-compose.yml - Wordpress with PHP-FPM and MySQL
services:
  wordpress-1:
    image: erikngigi/wordpress-php8.3-fpm:dev
    container_name: staging-dearaustinchicago-wp
    restart: unless-stopped
    volumes:
      # Bind mount for dearaustinchicago staging files
      - ${HOME}/wordpress-sites/dearaustinchicago/staging:/var/www/html:rw,cached
      - ./wordpress/settings/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    ports:
      - 9003:9000
    env_file:
      - .env-wp
    depends_on:
      wordpress-db1:
        condition: service_healthy
    networks:
      - wordpress-net

  wordpress-db1:
    image: mariadb:11.4
    container_name: staging-dearaustinchicago-db
    restart: unless-stopped
    env_file:
      - .env-db
    volumes:
      - wordpress-db-volume:/var/lib/mysql
      - ./wordpress/settings/mysql/wordpress.cnf:/etc/mysql/conf.d/wordpress.cnf:ro
    ports:
      - 3309:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wordpress-net

networks:
  wordpress-net:
    name: wordpress-net
    driver: bridge

volumes:
  wordpress-db-volume:
    name: wordpress-db-volume
    driver: local
