; custom.ini
memory_limit = 512M
max_execution_time = 60
max_input_vars = 3000
upload_max_filesize = 64M
post_max_size = 64M

[opcache]
opcache.enable = 1
opcache.memory_consumption = 256
opcache.max_accelerated_files = 20000
