name: Custom Wordpress PHP-FPM Docker image with WP-CLI
on:
  push:
    branches:
      - main
    paths:
      - "dockerfiles/**"
      - ".github/workflows/wordpress-build.yml"
  workflow_dispatch:
    inputs:
      tags:
        description: "Custom tag for the image (optional)"
        required: false
        default: "latest"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Login to Github Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./dockerfiles
          file: ./dockerfiles/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ vars.WORDPRESS_IMAGE_NAME }}:latest
      - name: Image build complete
        run: echo "✅ Custom Wordpress docker image built and pushed successfully."
